import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faChrome as fabChrome,
	faDiscord as fabDiscord,
	faEdge as fabEdge,
	faFirefox as fabFirefox,
	faGithub as fabGithub,
	faOpera as fabOpera,
	faCcPaypal as fabPaypal,
	faTwitch as fabTwitch,
	faTwitter as fabTwitter,
	faYoutube as fabYoutube,
} from "@fortawesome/free-brands-svg-icons";
import { faObjectUngroup, faCircleCheck as farCircleCheck } from "@fortawesome/free-regular-svg-icons";
import {
	faArrowLeft,
	faBars,
	faBox,
	faBrush,
	faBullseye,
	faCalendarAlt,
	faCheck,
	faCheckCircle,
	faCheckDouble,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircle,
	faClock,
	faCodeBranch,
	faColumns,
	faCopy,
	faCreditCard,
	faCube,
	faDownload,
	faEllipsisH,
	faEllipsisV,
	faEnvelope,
	faExclamation,
	faExclamationTriangle,
	faExternalLinkAlt,
	faEye,
	faEyeSlash,
	faFilter,
	faFire,
	faFlag,
	faGavel,
	faGear,
	faGift,
	faGlobe,
	faHashtag,
	faLanguage,
	faLayerGroup,
	faListCheck,
	faLock,
	faMinus,
	faMoon,
	faObjectGroup,
	faPalette,
	faPen,
	faPlus,
	faReply,
	faRotateRight,
	faSave,
	faSearch,
	faSlash,
	faSmile,
	faSquare,
	faStar,
	faSync,
	faTag,
	faTicket,
	faTimes,
	faTrash,
	faTrophy,
	faUndo,
	faUnlock,
	faUser,
	faUserClock,
	faUserLock,
	faUserMinus,
	faUserPen,
	faUserPlus,
	faUserSlash,
	faUsersCog,
	faWrench,
	faSun,
	faSquarePlus,
} from "@fortawesome/free-solid-svg-icons";

// import{
// 	faBookSparkles,
// 	faBullseyePointer,
// 	faCakeSlice,
// 	faChevronsDown,
// 	faChevronsRight,
// 	faFaceSunglasses,
// 	faHexagonPlus,
// 	faMegaphone,
// 	faPenField,
// 	faRectangleWide,
// 	faSeal,
// 	faSquareQuestion,
// 	faSunBright,
// 	faTimer,
// 	faTreeChristmas,
// 	faWaveformLines,
// } from "@fortawesome/sharp-solid-svg-icons";

library.add(
	faArrowLeft,
	faBars,
	fabChrome,
	fabDiscord,
	fabEdge,
	fabFirefox,
	fabGithub,
	fabOpera,
	faBox,
	fabPaypal,
	faBrush,
	fabTwitch,
	fabTwitter,
	faBullseye,
	fabYoutube,
	faCalendarAlt,
	faCheck,
	faCheckCircle,
	faCheckDouble,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircle,
	faClock,
	faCodeBranch,
	faColumns,
	faCopy,
	faCopy,
	faCreditCard,
	faCube,
	faDownload,
	faEllipsisH,
	faEllipsisV,
	faEnvelope,
	faExclamation,
	faExclamationTriangle,
	faExternalLinkAlt,
	faEye,
	faEyeSlash,
	faFilter,
	faFire,
	faFlag,
	faGavel,
	faGear,
	faGift,
	faGlobe,
	faHashtag,
	faLanguage,
	faLayerGroup,
	faListCheck,
	faLock,
	faMinus,
	faMoon,
	faObjectGroup,
	faObjectUngroup,
	faPalette,
	faPen,
	faPlus,
	farCircleCheck,
	faReply,
	faRotateRight,
	faSave,
	faSearch,
	faSearch,
	faSlash,
	faSmile,
	faSquare,
	faStar,
	faSync,
	faTag,
	faTicket,
	faTimes,
	faTrash,
	faTrophy,
	faUndo,
	faUnlock,
	faUser,
	faUserClock,
	faUserLock,
	faUserMinus,
	faUserPen,
	faUserPlus,
	faUsersCog,
	faUserSlash,
	faWrench,
	faSun,
	faSquarePlus,
);
