import { library } from "@fortawesome/fontawesome-svg-core";
import {
	faChrome as fabChrome,
	faDiscord as fabDiscord,
	faEdge as fabEdge,
	faFirefox as fabFirefox,
	faGithub as fabGithub,
	faOpera as fabOpera,
	faCcPaypal as fabPaypal,
	faTwitch as fabTwitch,
	faTwitter as fabTwitter,
	faYoutube as fabYoutube,
} from "@fortawesome/free-brands-svg-icons";
import { faObjectUngroup, faCircleCheck as farCircleCheck } from "@fortawesome/free-regular-svg-icons";
import {
	faAnglesDown,
	faAnglesRight,
	faArrowLeft,
	faBars,
	faBox,
	faBrush,
	faBullhorn,
	faBullseye,
	faCakeCandles,
	faCalendarAlt,
	faCalendarDays,
	faCertificate,
	faCheck,
	faCheckCircle,
	faCheckDouble,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircle,
	faCircleQuestion,
	faClapperboard,
	faClock,
	faCodeBranch,
	faColumns,
	faCopy,
	faCreditCard,
	faCrosshairs,
	faCube,
	faDownload,
	faEllipsisH,
	faEllipsisV,
	faEnvelope,
	faExclamation,
	faExclamationTriangle,
	faExternalLinkAlt,
	faEye,
	faEyeSlash,
	faFaceGrinStars,
	faFilm,
	faFilter,
	faFire,
	faFlag,
	faGavel,
	faGear,
	faGift,
	faGlobe,
	faHashtag,
	faLanguage,
	faLayerGroup,
	faListCheck,
	faLock,
	faMinus,
	faMoon,
	faObjectGroup,
	faPalette,
	faPen,
	faPenToSquare,
	faPlus,
	faReply,
	faRotateRight,
	faSave,
	faSearch,
	faSlash,
	faSmile,
	faSquare,
	faSquarePlus,
	faStar,
	faSun,
	faSync,
	faTag,
	faTicket,
	faTimes,
	faTrash,
	faTree,
	faTrophy,
	faUndo,
	faUnlock,
	faUser,
	faUserClock,
	faUserLock,
	faUserMinus,
	faUserPen,
	faUserPlus,
	faUserSlash,
	faUsersCog,
	faUsersGear,
	faWrench,
} from "@fortawesome/free-solid-svg-icons";

// import{
// 	faBookSparkles, -> faUsersGear
// 	faBullseyePointer, -> faCrosshairs
// 	faCakeSlice, -> faCakeCandles
// 	faChevronsDown, -> faAnglesDown
// 	faChevronsRight, -> faAnglesRight
// 	faFaceSunglasses, -> faFaceGrinStars
// 	faHexagonPlus, 	-> faSquarePlus
// 	faMegaphone, -> faBullhorn
// 	faPenField, -> faPenToSquare
// 	faRectangleWide, -> faClapperboard
// 	faSeal, -> faCertificate
// 	faSquareQuestion, -> faCircleQuestion
// 	faSunBright, -> faSun
// 	faTimer, -> faCalendarDays
// 	faTreeChristmas, -> faTree
// 	faWaveformLines, -> faFilm
// } from "@fortawesome/sharp-solid-svg-icons";

library.add(
	faArrowLeft,
	faBars,
	fabChrome,
	fabDiscord,
	fabEdge,
	fabFirefox,
	fabGithub,
	fabOpera,
	faBox,
	fabPaypal,
	faBrush,
	fabTwitch,
	fabTwitter,
	faBullseye,
	fabYoutube,
	faCalendarAlt,
	faCheck,
	faCheckCircle,
	faCheckDouble,
	faChevronDown,
	faChevronLeft,
	faChevronRight,
	faCircle,
	faClock,
	faCodeBranch,
	faColumns,
	faCopy,
	faCopy,
	faCreditCard,
	faCube,
	faDownload,
	faEllipsisH,
	faEllipsisV,
	faEnvelope,
	faExclamation,
	faExclamationTriangle,
	faExternalLinkAlt,
	faEye,
	faEyeSlash,
	faFilter,
	faFire,
	faFlag,
	faGavel,
	faGear,
	faGift,
	faGlobe,
	faHashtag,
	faLanguage,
	faLayerGroup,
	faListCheck,
	faLock,
	faMinus,
	faMoon,
	faObjectGroup,
	faObjectUngroup,
	faPalette,
	faPen,
	faPlus,
	farCircleCheck,
	faReply,
	faRotateRight,
	faSave,
	faSearch,
	faSearch,
	faSlash,
	faSmile,
	faSquare,
	faStar,
	faSync,
	faTag,
	faTicket,
	faTimes,
	faTrash,
	faTrophy,
	faUndo,
	faUnlock,
	faUser,
	faUserClock,
	faUserLock,
	faUserMinus,
	faUserPen,
	faUserPlus,
	faUsersCog,
	faUserSlash,
	faWrench,

	faSun,
	faSquarePlus,
	faUsersGear,
	faCrosshairs,
	faCakeCandles,
	faAnglesDown,
	faAnglesRight,
	faFaceGrinStars,
	faBullhorn,
	faPenToSquare,
	faClapperboard,
	faCertificate,
	faCircleQuestion,
	faCalendarDays,
	faTree,
	faFilm,
);
